const $=id=>document.getElementById(id);let current=null;
let shown=null;
function draw(m){shown=m;const c=$('qr'),ctx=c.getContext('2d'),bg=$('background').value==='yes',margin=bg?4:0,n=m.length+2*margin;ctx.clearRect(0,0,c.width,c.height);$('plate').classList.toggle('no-background',!bg);if(bg){ctx.fillStyle='#fffef8';ctx.fillRect(0,0,c.width,c.height);}ctx.fillStyle='#233b32';m.forEach((row,y)=>row.forEach((v,x)=>{if(v){const a=Math.round((x+margin)*c.width/n),b=Math.round((y+margin)*c.height/n);ctx.fillRect(a,b,Math.round((x+margin+1)*c.width/n)-a,Math.round((y+margin+1)*c.height/n)-b);}}));}
function invalidate(){current=null;$('download').disabled=true;$('status').textContent='تم تغيير الإعدادات · اضغط توليد المجسّم';$('error').textContent='';$('warning').textContent='';}
$('url').addEventListener('input',invalidate);for(const id of ['base','relief'])$(id).addEventListener('change',invalidate);
$('form').addEventListener('submit',e=>{e.preventDefault();invalidate();try{let value=$('url').value.trim();if(!value)throw Error('ألصق الرابط أولًا.');if(!/^[a-z][a-z0-9+.-]*:/i.test(value))value='https://'+value;let u;try{u=new URL(value);}catch{throw Error('تحقق من كتابة الرابط، مثل https://example.com');}if(!['https:','http:'].includes(u.protocol)||!u.hostname.includes('.'))throw Error('أدخل رابط موقع صالح يبدأ بـ https:// أو http://');const m=QRPlate.matrix(u.href),cell=40/(m.length+8);if(cell<.55)throw Error('الرابط طويل جدًا لصفيحة ٤ سم. استخدم رابطًا أقصر لتحسين الطباعة.');current={m,base:+$('base').value,relief:+$('relief').value};draw(m);$('download').disabled=false;$('status').textContent='جاهز للتنزيل · المربع '+cell.toFixed(2)+' مم';$('printnote').textContent='غيّر لون الخيط عند ارتفاع '+current.base+' مم، أو لوّن السطح البارز. ملف STL لا يحفظ الألوان.';if(cell<.8)$('warning').textContent='هذا الرابط ينتج تفاصيل صغيرة ('+cell.toFixed(2)+' مم). رابط أقصر يعطي رمزًا أسهل للطباعة؛ اختبر دقة طابعتك وقراءة الرمز.';}catch(err){$('error').textContent=err.message||'تعذر توليد الرمز. جرّب رابطًا أقصر.';$('status').textContent='لم يُولّد المجسّم بعد';$('url').focus();}});
$('download').addEventListener('click',()=>{if(!current)return;const data=QRPlate.stl(QRPlate.mesh(current.m,current.base,current.relief,current.background)),url=URL.createObjectURL(new Blob([data],{type:'model/stl'})),a=document.createElement('a');a.href=url;a.download='RavenLab-QR-'+(current.background?'plate':'no-background')+'-40mm.stl';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('status').textContent='تم تجهيز STL · افتحه بوحدة المليمتر';});
function mode(){const bg=$('background').value==='yes';$('base').disabled=!bg;$('modehint').textContent=bg?'المقاس ٤٠ × ٤٠ مم يشمل القاعدة والهامش.':'الرمز نفسه ٤٠ × ٤٠ مم دون قاعدة. مربعات منفصلة؛ ثبّتها على سطح فاتح مع هامش فارغ بعرض ٤ مربعات.';}
$('background').addEventListener('change',()=>{invalidate();mode();if(shown)draw(shown);});
$('form').addEventListener('submit',()=>{if(!current)return;current.background=$('background').value==='yes';if(!current.background){current.base=0;$('printnote').textContent='اطبع الرمز بلون داكن وثبّت مربعاته بترتيبها على سطح فاتح. ارتفاع الرمز هو السماكة الكلية.';$('warning').textContent+=' بدون خلفية: الملف يحتوي مربعات منفصلة. اترك على سطح التثبيت هامشًا فاتحًا لا يقل عن '+(160/current.m.length).toFixed(2)+' مم حول الرمز.';}if(current.relief===.2||current.base===.2)$('warning').textContent+=' سماكة ٠٫٢ مم رقيقة جدًا؛ اضبط ارتفاع طبقة الطباعة بما يناسبها وتعامل معها بحذر.';$('status').textContent='جاهز · الارتفاع الكلي '+(current.base+current.relief).toFixed(1)+' مم';});
for(const id of ['three','flat'])$(id).addEventListener('click',()=>{$('plate').classList.toggle('flat',id==='flat');for(const key of ['three','flat']){$(key).classList.toggle('selected',id===key);$(key).setAttribute('aria-pressed',String(id===key));}});
try{draw(QRPlate.matrix('https://example.com'));}catch{$('error').textContent='تعذر تحميل مولّد QR. أعد فتح الصفحة.';}

