import {threeMF,zip} from './package3mf.mjs';
const el=id=>document.getElementById(id);
const original=document.querySelector('.workspace');
const tabs=document.createElement('div');tabs.className='mode-tabs';tabs.innerHTML='<button id="upload-mode" class="active" aria-pressed="true">QR أسفل مجسّم STL</button><button id="plate-mode" aria-pressed="false">صفيحة QR مستقلة</button>';original.before(tabs);
const panel=document.createElement('section');panel.className='import-panel';panel.innerHTML=`
<div class="import-controls"><div class="section-title"><span class="step">01</span><h2>مجسّمك + رابطك</h2></div>
<form id="solid-form"><label for="stl-file">ارفع المجسّم الأصلي</label><input type="file" id="stl-file" accept=".stl" required><p id="file-info" class="muted">STL حتى ١٥ ميغابايت · المليمتر · لا نرفع ملفك إلى خادم</p>
<label for="solid-url">الرابط داخل رمز QR</label><input id="solid-url" dir="ltr" inputmode="url" placeholder="https://example.com" maxlength="500" required>
<div class="fields"><div><label for="qr-size">حجم QR مع الهامش (مم)</label><input id="qr-size" type="number" value="28" min="10" max="120" step="0.5" required></div><div><label for="qr-depth">سماكة طبقة الرمز (مم)</label><input id="qr-depth" type="number" value="0.4" min="0.2" max="2" step="0.1" required></div></div>
<label for="solid-style">طريقة الدمج أسفل المجسّم</label><select id="solid-style"><option value="flush" selected>مستوٍ مع الأسفل — لونان على السرير</option><option value="engrave">حفر داخل السطح — أسفل مستوٍ</option><option value="emboss">رمز بارز إلى الخارج</option></select>
<label class="check-option"><input id="solid-pad" type="checkbox" checked> إضافة قاعدة رقيقة متصلة بالأسفل</label><p class="muted">تغطي الفتحات تحت الرمز. سماكتها ٠٫٨ مم على الأقل وتزداد إذا زاد عمق الحفر. بإلغاء الخيار يُدمج الرمز مباشرة في سطح مسطّح موجود.</p>
<div class="fields"><div><label for="qr-x">الموضع الأفقي X (مم)</label><input id="qr-x" type="number" value="0" step="0.5" required></div><div><label for="qr-y">الموضع العمودي Y (مم)</label><input id="qr-y" type="number" value="0" step="0.5" required></div></div>
<p class="muted">الأسفل هو أدنى سطح على محور Z في ملفك. لا نغيّر حجم المجسّم. الإطار في المعاينة يوضح مكان الرمز وهامشه.</p>
<p id="solid-error" role="alert"></p><button id="solid-build" class="primary" type="submit" disabled>دمج الرمز مع المجسّم</button></form>
<button id="solid-download" class="download" disabled>تنزيل المجسّم المدمج STL ↓</button><button id="solid-parts" class="cancel" hidden>تنزيل جزأين STL للطباعة بلونين</button><button id="solid-cancel" class="cancel" hidden>إلغاء المعالجة</button>
</div><div class="import-preview"><div class="preview-head"><h2>معاينة المجسّم</h2><span class="badge">مقياس المجسّم محفوظ</span></div><div class="viewer-tools"><button data-view="bottom" aria-pressed="true">من الأسفل</button><button data-view="iso" aria-pressed="false">مجسّم</button><button data-view="top" aria-pressed="false">من الأعلى</button><button id="rotate-left" aria-label="تدوير يسارًا">↶</button><button id="rotate-right" aria-label="تدوير يمينًا">↷</button></div><canvas id="solid-canvas" width="900" height="850" aria-label="معاينة ثلاثية الأبعاد للمجسّم وموضع رمز QR"></canvas><p id="solid-status" role="status">ارفع مجسّمًا لبدء المعاينة.</p><p class="viewer-note">الوضع المستوي: الجسم والرمز على السرير عند Z=0 بلا بروز. استورد 3MF كجسم واحد متعدد الأجزاء واختر خيطًا فاتحًا للجسم وداكنًا للرمز. قد تحتاج تعيين الخيوط يدويًا في برنامج التقطيع؛ الطباعة بلونين في الطبقة نفسها تتطلب تبديل مواد مناسبًا. STL واحد لا يحفظ الألوان. اسحب لتدوير العرض. لوّن الرمز بلون داكن والخلفية بلون فاتح واختبر مسحه بعد الطباعة. للحفر: يمكن ملء التجاويف بلون داكن. للبروز: اختر اتجاه الطباعة والدعامات في برنامج التقطيع.</p></div>`;
original.before(panel);original.hidden=true;document.querySelector('.notes').hidden=true;
document.querySelector('.intro p').textContent='ارفع مجسّم STL وأضف رابطك، واحصل على مجسّم واحد يحمل رمز QR على وجهه السفلي.';
for(const mode of ['upload','plate'])el(mode+'-mode').onclick=()=>{const upload=mode==='upload';panel.hidden=!upload;original.hidden=upload;document.querySelector('.notes').hidden=upload;el('warning').hidden=upload;for(const key of ['upload','plate']){el(key+'-mode').classList.toggle('active',key===mode);el(key+'-mode').setAttribute('aria-pressed',String(key===mode));}if(upload)render();};
let worker=null,sequence=0,pending=new Map(),source=null,result=null,filename='model',view='bottom',spin=0,tilt=.65,busy=false;
function getWorker(){if(!worker){worker=new Worker(new URL('./solid-worker.mjs',import.meta.url),{type:'module'});worker.onmessage=e=>{const p=pending.get(e.data.id);if(p){pending.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data);}};worker.onerror=()=>{for(const p of pending.values())p.reject(Error('تعذر تشغيل محرّك الدمج. افتح الموقع من رابطه وأعد المحاولة.'));pending.clear();worker.terminate();worker=null;};}return worker;}
function request(type,data){return new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});getWorker().postMessage({id,type,...data});});}
function controls(){el('solid-build').disabled=!source||busy;el('solid-download').disabled=!result||busy;el('solid-cancel').hidden=!busy;el('solid-parts').hidden=!result?.qrTriangles;el('solid-parts').disabled=busy;el('solid-download').textContent=result?.qrTriangles?'تنزيل المجسّم المدمج 3MF ↓':'تنزيل المجسّم المدمج STL ↓';for(const input of panel.querySelectorAll('input,select'))input.disabled=busy;}
function resetResult(){result=null;el('solid-error').textContent='';controls();if(source)el('solid-status').textContent='المعاينة الأصلية · اضغط دمج لتحديث الناتج';render();}
function opts(){return {size:+el('qr-size').value,depth:+el('qr-depth').value,x:+el('qr-x').value,y:+el('qr-y').value,style:el('solid-style').value,pad:el('solid-pad').checked};}
el('stl-file').onchange=async()=>{source=null;result=null;controls();render();const file=el('stl-file').files[0];if(!file)return;try{if(file.size>15*1024*1024)throw Error('اختر ملفًا أقل من ١٥ ميغابايت.');if(!/\.stl$/i.test(file.name))throw Error('اختر ملف STL.');busy=true;controls();el('solid-status').textContent='قراءة المجسّم…';el('solid-error').textContent='';source=await request('load',{buffer:await file.arrayBuffer()});filename=file.name.replace(/\.stl$/i,'');el('file-info').textContent=file.name+' · '+source.size.map(v=>v.toFixed(2)).join(' × ')+' مم';el('qr-size').value=Math.min(28,Math.floor(Math.min(source.size[0],source.size[1])*.6));el('qr-x').value='0';el('qr-y').value='0';el('solid-status').textContent='تم تحميل المجسّم · الإطار يحدد موضع الرمز';view='bottom';render();}catch(e){source=null;el('solid-error').textContent=e.message;el('solid-status').textContent='تعذرت قراءة الملف';}finally{busy=false;controls();}};
for(const id of ['solid-url','qr-size','qr-depth','qr-x','qr-y','solid-style','solid-pad'])el(id).addEventListener('input',resetResult);
el('solid-form').onsubmit=async e=>{e.preventDefault();if(!source||busy)return;resetResult();try{let url=el('solid-url').value.trim();if(!/^[a-z][a-z0-9+.-]*:/i.test(url))url='https://'+url;let u;try{u=new URL(url);}catch{throw Error('أدخل رابط موقع صالحًا.');}if(!['http:','https:'].includes(u.protocol)||!u.hostname.includes('.'))throw Error('أدخل رابطًا يبدأ بـ https:// أو http://');const matrix=window.QRPlate.matrix(u.href);busy=true;controls();el('solid-status').textContent='جارٍ دمج الأسطح والتحقق من اتصال المجسّم…';result=await request('build',{matrix,options:opts()});result.options=opts();el('solid-status').textContent=(result.qrTriangles?'جاهز · جزآن متطابقا الموضع، بلا بروز · حجم مربع QR ':'جاهز · '+result.components+' جسم · حجم مربع QR ')+result.cell.toFixed(2)+' مم'+(result.cell<.8?' · تفاصيل دقيقة؛ جرّب رابطًا أقصر':'');render();}catch(err){result=null;el('solid-error').textContent=err.message||'تعذر الدمج';el('solid-status').textContent='لم يُنشأ ملف جديد؛ عدّل الإعدادات ثم جرّب مجددًا.';}finally{busy=false;controls();}};
el('solid-download').onclick=()=>{if(!result)return;const flush=!!result.qrTriangles,data=flush?threeMF(result):window.QRPlate.stl(result.triangles),url=URL.createObjectURL(new Blob([data],{type:flush?'model/3mf':'model/stl'})),a=document.createElement('a');a.href=url;a.download=filename+'-RavenLab-QR.'+(flush?'3mf':'stl');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
el('solid-cancel').onclick=()=>{worker?.terminate();worker=null;for(const p of pending.values())p.reject(Error('تم إلغاء المعالجة. أعد اختيار الملف للمتابعة.'));pending.clear();source=null;result=null;busy=false;el('stl-file').value='';controls();render();};
const canvas=el('solid-canvas'),ctx=canvas.getContext('2d');
function render(){const W=canvas.width,H=canvas.height;ctx.fillStyle='#e9ede5';ctx.fillRect(0,0,W,H);if(!source){ctx.fillStyle='#52645c';ctx.font='24px Tahoma';ctx.textAlign='center';ctx.fillText('ارفع ملف STL لمشاهدة المجسّم هنا',W/2,H/2);return;}
 const tris=result?.triangles||source.triangles,o=result?.options||opts(),scale=Math.min(W,H)*.72/Math.max(...source.size,o.size||0),s=Math.sin(spin),c=Math.cos(spin),t=view==='iso'?tilt:0;
 const project=v=>{let x=v[0]*c-v[1]*s,y=v[0]*s+v[1]*c,z=v[2];if(view==='top')return [W/2+x*scale,H/2-y*scale,z];return [W/2+x*scale,H/2+(y*Math.cos(t)+z*Math.sin(t))*scale,y*Math.sin(t)-z*Math.cos(t)];};
 const faces=tris.map((tri,index)=>{const p=tri.map(project);return {p,tri,index,d:(p[0][2]+p[1][2]+p[2][2])/3};}).sort((a,b)=>a.d-b.d);
 for(const {p,tri,index} of faces){const a=tri[0],b=tri[1],c=tri[2],u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),nz=u[0]*v[1]-u[1]*v[0],nx=u[1]*v[2]-u[2]*v[1],ny=u[2]*v[0]-u[0]*v[2],l=Math.hypot(nx,ny,nz)||1;const qrZ=result?result.surfaceZ+(o.style==='engrave'?o.depth:-o.depth):NaN,dark=result&&(result.qrTriangles?index>=result.bodyTriangles.length:nz/l<-.99&&tri.every(v=>Math.abs(v[2]-qrZ)<.0001));const shade=Math.round(74+25*Math.abs((nx*.3+ny*.4+nz*.8)/l));ctx.fillStyle=dark?'#203a31':`hsl(88 13% ${shade}%)`;ctx.beginPath();ctx.moveTo(p[0][0],p[0][1]);ctx.lineTo(p[1][0],p[1][1]);ctx.lineTo(p[2][0],p[2][1]);ctx.closePath();ctx.fill();}
 if(!result&&view!=='top'&&Number.isFinite(o.size)){const q=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>project([o.x+x*o.size/2,o.y+y*o.size/2,-.1]));ctx.strokeStyle='#456a2c';ctx.lineWidth=3;ctx.setLineDash([10,7]);ctx.beginPath();q.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.stroke();ctx.setLineDash([]);}
}
for(const button of panel.querySelectorAll('[data-view]'))button.onclick=()=>{view=button.dataset.view;spin=0;for(const b of panel.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b===button));render();};
el('rotate-left').onclick=()=>{spin-=Math.PI/12;render();};el('rotate-right').onclick=()=>{spin+=Math.PI/12;render();};let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;view='iso';spin+=(e.clientX-drag[0])*.008;tilt=Math.max(-1.5,Math.min(1.5,tilt+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];render();};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;render();

el('solid-parts').onclick=()=>{if(!result?.qrTriangles)return;const shift=t=>t.map(tri=>tri.map(p=>[p[0],p[1],Number((p[2]-result.surfaceZ).toFixed(6))])),bytes=zip({'RavenLab-Body.stl':window.QRPlate.stl(shift(result.bodyTriangles)),'RavenLab-QR.stl':window.QRPlate.stl(shift(result.qrTriangles)),'READ-ME.txt':'Import both STL files together as parts of ONE object. Preserve relative coordinates. Assign a light filament to Body and dark filament to QR. Both start at Z=0. Do not auto-arrange them separately.'}),url=URL.createObjectURL(new Blob([bytes],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download=filename+'-RavenLab-two-parts.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};

